import Head from "next/head";
// import { Inter } from "@next/font/google";
import Center from "@/stories/Center";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Diet App</title>
        <meta name="description" content="Generated by Diet app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Center msg="ハロー" />
      </main>
    </>
  );
}
