import Head from "next/head";
// import { Inter } from "@next/font/google";

// components------------------------
import { Page } from "@/stories/Page";
import LineChart from "@/stories/chart/LineChart";
import DietList from "@/stories/DietList";
import ProgressChart from "@/stories/chart/ProgressChart ";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Diet App</title>
        <meta name="description" content="Generated by Diet app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>
        <div className="w-4/5 m-auto ">
          <div className=" grid grid-cols-2 gap-4 mb-20">
            <ProgressChart />
            <LineChart />
          </div>

          <DietList />
        </div>
      </Page>
    </>
  );
}
